### PR TITLE
Sanitize and test vector<bool> specializations

### PR DESCRIPTION
**Pull request by roystgnr**
@NamjaeChoi - can you see if this still gives you `-fsanitize=integer` complaints?  I'll need to do a little futzing to get a clang+MPI build working myself.

### CODE REVIEW

**Comment by NamjaeChoi** [comment]
I think this removes the complaint.

**Comment by NamjaeChoi** [comment]
Only the following complaint remains related with `parallel_implementation.h`:

> /Users/choin/projects/griffin/moose/scripts/../libmesh/installed/include/timpi/parallel_implementation.h:4055:3: runtime error: implicit conversion from type 'unsigned int' of value 4294967294 (32-bit, unsigned) to type 'int' changed the value to -2 (32-bit, signed)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/choin/projects/griffin/moose/scripts/../libmesh/installed/include/timpi/parallel_implementation.h:4055:3 in

**Comment by roystgnr** [comment]
I'll see if I can reproduce that in a libMesh run; I think I've figured out the clang+MPI situation.  I don't suppose you can trigger it via the core MOOSE framework at most?

**Comment by roystgnr** [comment]
Whoa, I seem to be able to trigger it in TIMPI alone.

**Comment by roystgnr** [comment]
Is there a way to get `-fsanitize=integer` errors to be fatal?  For now I can check `run_unit_tests.sh.log`, but if I could actually stop the unit tests from passing then we could get regression coverage for this later.  The TIMPI test suite runs really fast.

I tried adding `-fno-sanitize-recover=integer` too but it didn't seem to change anything.

**Comment by roystgnr** [comment]
Would you see how things work for you with these last two commits?  Those seem to fix all the fsanitize issues I can trigger at the TIMPI level alone.

**Comment by NamjaeChoi** [comment]
I also confirmed that it removes all the MPI-related complaints. Thanks.

**Pull request merged**
