### PR TITLE
Avoid shadowed declarations introduced in #66

### PR DESCRIPTION
**Pull request by loganharbour**
Refs #66

### CODE REVIEW

**Comment by loganharbour** [comment]
@lindsayad think we're gonna need a 1.6.1

**Comment by loganharbour** [comment]
@roystgnr

**Review by lindsayad — APPROVED** [review]

**Comment by lindsayad** [comment]
I am going to try the timpi update on libmesh/libmesh#2881 with a temporary bootstrapped branch before I tag anything again

**Comment by roystgnr** [comment]
Nice fix.  This is a better API than letting comm possibly change from call to call.

**Pull request merged**
