### PR TITLE
Carry rvalue references through the nbx helper

### PR DESCRIPTION
**Pull request by lindsayad**
We do so with the public APIs so let's do it with the helper too

### CODE REVIEW

**Review by loganharbour — APPROVED** [review]
👍🏼 looks good to me

not sure why we didn't do this previously...

**Review by loganharbour — CHANGES_REQUESTED** [review]
Shouldn't we still test the reference case? I suspect folks have implemented the lambda as non auto and don't pass in an rvalue ref

**Comment by lindsayad** [comment]
if the action functor takes the data as an lvalue reference then with the change here, their code fails to compile, hence why I had to change the unit tests here. But if their action functor takes the data as a const lvalue reference then their code will still work. In MOOSE when compiling the contact module, there was only one action functor I had to change, and it was in the framework `LowerDBlocksFromSidesetGenerator`

**Review by loganharbour — CHANGES_REQUESTED** [review]
We should update the doxygen to reflect this; I was just working with @grmnptr and he was confused because the documentation explicitly says you get a const ref to the received containers. Not very intuitive when you're trying to use move semantics

**Review by loganharbour — APPROVED** [review]

**Comment by lindsayad** [comment]
@roystgnr I'm going to wait until you approve before merging

**Review by roystgnr — APPROVED** [review]
I always hate having to change a test case or user code, but we really did never intend to support non-const lvalue references there.

**Pull request merged**
