### PR TITLE
Default constructor and destructor in Status

### PR DESCRIPTION
**Pull request by loganharbour**
@jwpeterson 

Screen Shot 2020-07-29 at 1 19 09 PM

### CODE REVIEW

**Comment by loganharbour** [comment]
@roystgnr was too quick for me to even get this one in!

**Comment by roystgnr** [comment]
Sorry!  I figured you were busy enough that you might want to just worry about the bugfix commit and less about the code-syntax-improvements commit.

**Comment by loganharbour** [comment]
I'm still in grad school - mindless alternative work makes for a good break!

**Comment by jwpeterson** [comment]
If it's default, it's not me fault.

**Pull request merged**
