### PR TITLE
Do not use std::remove_if, which moves data

### PR DESCRIPTION
**Pull request by loganharbour**

### CODE REVIEW

**Comment by loganharbour** [comment]
@cticenhour here's the fix. It adds an extra branch within a loop (which is what we tried to avoid 😢)

**Comment by cticenhour** [comment]
Hitting this error during libmesh build after the final linking of `libdbg`, `libopt`, and `libdevel`. Do I need to bootstrap or manually configure TIMPI within `moose/libmesh/contrib'? I was under the impression that configuration was occurring on the libmesh install script level. 

```
make[4]: Leaving directory '/Users/user/projects/moose/libmesh/build/contrib/fparser'
make[3]: Leaving directory '/Users/user/projects/moose/libmesh/build/contrib/fparser'
make[2]: Leaving directory '/Users/user/projects/moose/libmesh/build/contrib/fparser'
Making all in nanoflann
make[2]: Entering directory '/Users/user/projects/moose/libmesh/build/contrib/nanoflann'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/Users/user/projects/moose/libmesh/build/contrib/nanoflann'
Making all in timpi
make[2]: Entering directory '/Users/user/projects/moose/libmesh/build/contrib/timpi'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/Users/user/projects/moose/libmesh/build/contrib/timpi'
make[1]: *** [Makefile:1034: all-recursive] Error 1
make[1]: Leaving directory '/Users/user/projects/moose/libmesh/build/contrib'
make: *** [Makefile:32810: all-recursive] Error 1
```

**Comment by roystgnr** [comment]
> Do I need to bootstrap

If you switched out the libMesh TIMPI hash (v1.8.1_bootstrapped) for the final hash here?  Yeah, exactly.  When we actually merge this into libMesh we'll make a 1.8.2 release tag and branch with a bootstrapped tag for the libMesh submodule, but right here there's no bootstrap files in git.

**Comment by lindsayad** [comment]
I'm going to test this on https://moosedevelopers.slack.com/archives/C010M4X8ZK2/p1642138858010400

**Comment by cticenhour** [comment]
Getting all green on Freya with this change!

**Comment by lindsayad** [comment]
This also fixes the failed assertions on the NS input

**Comment by roystgnr** [comment]
Fantastic.  I'm making this 1.8.2 and moving it downstream.

**Comment by loganharbour** [comment]
Thanks folks. Sorry for the misunderstanding of `std::remove_if`

**Comment by roystgnr** [comment]
Hey, don't blame yourself for this.  I wrote the too-fragile class that broke, I reviewed the PR that broke it, and before you submitted the PR I **specifically answered your question about whether `std::remove_if` was safe to use here** with an overconfident "yes".

**Pull request merged**
